-- 创建banner_settings表
create table if not exists banner_settings (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null,
  background_image text,
  background_color text not null default '#3B82F6',
  text_color text not null default '#FFFFFF',
  is_active boolean not null default true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 权限设置
alter table banner_settings enable row level security;

-- 创建RLS策略
create policy "Anyone can view banner_settings" on banner_settings
  for select using (true);

create policy "Authenticated users can insert/update/delete banner_settings" on banner_settings
  for all using (auth.role() = 'authenticated');
